server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/myNeighborhood?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:MartinEden1909!}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  multipart:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        messaging: trace
        web:
          socket: trace